apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Danor93/ecommerce-cicd-pipeline.git
