# ----------------------------------------------------------------------------
# Kustomization for Argo CD declarative resources
# Includes projects, applications and bootstrap app under this directory.
# ----------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: argocd-resources
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  # ArgoCD Projects
  - projects/ecommerce-project.yaml

  # ArgoCD Applications
  - applications/ecommerce-app.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: ecommerce-platform

namespace: argocd
